export const CMS_NAME = 'Sanity'
export const CMS_URL = 'https://sanity.io/'
export const HOME_OG_IMAGE_URL = 'https://c8c1-118-208-248-252.au.ngrok.io/thub-front.png'
export const TWITTER = 'https://twitter.com/tokenomicsdao'
export const DISCORD = 'https://discord.gg/msHySHqrVN'
export const LINKTREE = 'https://linktr.ee/tokenomicsdao'
export const YOUTUBE = 'https://www.youtube.com/c/TokenomicsDAO'
export const DISCORD_WEBHOOK = 'https://discordapp.com/api/webhooks/1032495484813709342/HXN6cpJvV2lVrGBjhWMbedRBLew_6FyS8cen2oVvnNVzyWu5tMnnopPuiohmqBlRMaYf'