// export const CMS_NAME = 'Sanity'
// export const CMS_URL = 'https://sanity.io/'
export const WEBSITE_URL_BASE = 'https://www.tokenomicshub.xyz'
export const HOME_OG_IMAGE_URL = `${WEBSITE_URL_BASE}/thub-front.png` //'https://www.tokenomicshub.xyz/thub-front.png'
export const TWITTER = 'https://twitter.com/tokenomicsdao'
export const DISCORD = 'https://discord.gg/msHySHqrVN'
export const LINKTREE = 'https://linktr.ee/tokenomicsdao'
export const YOUTUBE = 'https://www.youtube.com/c/TokenomicsDAO'